name: dmcgen
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - pillow==6.2.0
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - scikit-image
    - seaborn
    - tqdm
